name=TARS
version=0.1.0
author=UN-Robotics Team
maintainer=UN-Robotics Team <contacto@un-robotics.org>
sentence=Libreria educativa para controlar actuadores, sensores y comunicaciones en robots con ESP32.
paragraph=API simple para alumnos: motores, servo, infrarrojo, ultrasonido, magnetico, sensor RGB y Bluetooth.
category=Device Control
url=https://github.com/UN-Robotics/UN-Robotics
architectures=esp32
includes=TARS.h
depends=ESP32Servo, Adafruit TCS34725, Adafruit BusIO
