name=TARS
version=0.9.0
author=TARS-Robotics Team
maintainer=TARS-Robotics Team <software@tarsupv.com>
sentence=Libreria educativa para controlar actuadores, sensores y comunicaciones en robots con ESP32.
paragraph=API simple para alumnos: motores, servo, infrarrojo, ultrasonido, magnetico, sensor RGB y Bluetooth.
category=Device Control
url=https://github.com/UPV-TARS/UN-Robotics
architectures=esp32
includes=TARS.h
depends=ESP32Servo, Adafruit TCS34725, Adafruit BusIO
